spring:
  application:
    name: kotlin-starter
  messages:
    encoding: UTF-8

server:
  port: 9022
  error:
    whitelabel:
      enabled: false


logging:
  level:
    root: ERROR
  config: classpath:log4j2.xml
